services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
    ports:
      - "8080:80"
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./.env:/var/www/html/.env
      - ./app:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
